# -*- coding: utf-8 -*-
"""Recommender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N4rkWgxIYJo9lN-Bj6jKUqD1pRZTHrDZ
"""

# Commented out IPython magic to ensure Python compatibility.
#!pip install streamlit scikit-surprise
# %pip install "numpy<2.0"
# %pip install scikit-surprise

import os

import streamlit as st
import pandas as pd
from google import genai
from pydantic import BaseModel, Field
from surprise import KNNBasic, Dataset, Reader, BaselineOnly
from google.genai.types import HttpOptions

# ---------------------------------------------------------------- page setup
st.set_page_config(
    page_title="Book Recommender",
    page_icon="🎬",
    layout="wide",
)


# ------------------------------------------------------------ data and model
# Caching strategy:
#   @st.cache_data     for return values that should be copied per session
#                      (DataFrames, dicts of immutable values).
#   @st.cache_resource for objects we want to share across all sessions of
#                      the running app (the fitted model — fitting is slow).

@st.cache_data
def load_data():
    """Load the Books/Ratings CSVs safely and build a book_id -> title lookup."""
    # Handle line endings and drop hidden BOM/spaces from column headers
    books = pd.read_csv("Books.csv", encoding="utf-8-sig", lineterminator="\n")
    ratings = pd.read_csv("Ratings.csv", encoding="utf-8-sig", lineterminator="\n")
    
    books.columns = books.columns.str.replace("\r", "").str.strip()
    ratings.columns = ratings.columns.str.replace("\r", "").str.strip()
    
    # Strip carriage returns and whitespace from text data strings
    if "title" in books.columns:
        books["title"] = books["title"].str.replace("\r", "").str.strip()
    if "genres" in books.columns:
        books["genres"] = books["genres"].str.replace("\r", "").str.strip()

    title_of = dict(zip(books["book_id"], books["title"]))
    return books, ratings, title_of


@st.cache_resource
def fit_ubcf_model():
    """Fit User-Based CF once on the full dataset, reuse for every request."""
    _, ratings, _ = load_data()
    reader = Reader(rating_scale=(0.5, 5.0))
    data = Dataset.load_from_df(ratings[["book_id", "user_id", "rating"]], reader)
    trainset = data.build_full_trainset()

    model = BaselineOnly(verbose=False)
    model.fit(trainset)
    return model


def recommend(model, user_id, min_ratings, top_n=10):
    """Return top-N candidate dicts for `user_id`, excluding movies with
    fewer than `min_ratings` ratings and movies the user has already rated.
    Each candidate carries the title, predicted rating, n_ratings, and
    avg_rating (the movie's mean rating across all users)."""
    books, ratings, title_of = load_data()

    counts = ratings["book_id"].value_counts()
    avg_rating = ratings.groupby("book_id")["rating"].mean()
    popular = set(counts[counts >= min_ratings].index)

    seen = set(ratings.loc[ratings["user_id"] == user_id, "book_id"])
    scored = [
        {
            "book_id": m,
            "title": title_of[m],
            "predicted": model.predict(user_id, m).est,
            "n_ratings": int(counts.get(m, 0)),
            "avg_rating": float(avg_rating.get(m, 0.0)),
        }
        for m in books["book_id"]
        if m not in seen and m in popular
    ]
    scored.sort(key=lambda r: -r["predicted"])
    return scored[:top_n]


# -------------------------------------------------------------- LLM section
# This mirrors the Week 4 demo: one generate_content call with a Pydantic
# response_schema, so response.parsed hands back validated objects (no manual
# JSON parsing).

class Pick(BaseModel):
    title: str = Field(description="Exact movie title from the candidate list.")
    reason: str = Field(description="One sentence on why it fits the user's request.")


# Same model as the demo: gemini-2.5-flash-lite has generous free limits and is
# plenty for this small re-ranking task.
GEMINI_MODEL = "gemini-2.5-flash-lite"

@st.cache_resource
def get_gemini_client():
    """Injects the key into the OS environment variables to fix the AQ. key bug."""
    api_key = None
    try:
        api_key = st.secrets.get("GEMINI_API_KEY")
    except (FileNotFoundError, KeyError):
        pass
    
    api_key = api_key or os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return None
        
    # FORCE the key directly into the OS environment variables.
    # The SDK automatically scans these when instantiated without parameters.
    os.environ["GEMINI_API_KEY"] = api_key
    
    # Return a completely blank initialization. This forces the SDK 
    # to treat your AQ. key as a raw, direct developer API key.
    return genai.Client()

def rerank_with_gemini(candidates, mood):
    """Ask Gemini to re-rank `candidates` by fit to the user's mood. Returns a
    list of `Pick`. Raises on auth/network errors so the caller can surface
    them in the UI."""
    client = get_gemini_client()
    if client is None:
        raise RuntimeError("Gemini API key not configured.")

    # Since Books.csv doesn't have genres, we simplify the catalog 
    # to just a clean list of book titles for the prompt.
    catalog = "\n".join(
        f"- {c['title']}"
        for c in candidates
    )

    system_instruction = (
        "You are a book concierge. The candidate books below were already "
        "picked for this user by collaborative filtering. Re-rank them by how "
        "well they fit the user's request, best first, and give each a "
        "one-sentence reason. Use the exact titles from the list and keep "
        "every candidate."
    )

    # Send just the mood and the list of titles to Gemini
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=f"User's request: {mood}\n\nBooks:\n{catalog}",
        config={
            "system_instruction": system_instruction,
            "response_mime_type": "application/json",
            "response_schema": list[Pick],
        },
    )
    return response.parsed


# ------------------------------------------------------------------- UI ----
st.title("🎬 Book Recommender")
st.caption("User-Based Collaborative Filtering on MovieLens")

with st.spinner("Loading data and fitting UBCF model…"):
    books, ratings, title_of = load_data()
    ubcf = fit_ubcf_model()

# ---- Sidebar: user input ----
with st.sidebar:
    st.header("Settings")

    user_ids = sorted(ratings["user_id"].unique())
    min_id, max_id = int(user_ids[0]), int(user_ids[-1])
    user_id_input = st.text_input(
        "User ID",
        value=str(min_id),
        help="Enter the ID of the user you want recommendations for.",
    )
    st.caption(f"Valid IDs: {min_id}–{max_id} · {len(user_ids)} users in the dataset")

    min_ratings = st.slider(
        "Minimum ratings per book",
        min_value=1,
        max_value=200,
        value=20,
        step=1,
        help=(
            "Hide rarely-rated book — CF can score a film 5/5 on just 1–2 "
            "ratings. Raise this to surface well-known titles."
        ),
    )

# ---- Main panel: recommendations ----
# The text box hands us a string, so validate it: it must be numeric, and the
# ID must actually exist in the data. IDs can have gaps (especially in larger
# datasets), and an unknown user would otherwise get a meaningless global-
# average prediction from CF. If so, return a clear message.
if not user_id_input.strip().isdigit():
    st.warning(f"Enter a numeric user ID between {min_id} and {max_id}.")
    st.stop()

user_id = int(user_id_input)
if user_id not in set(user_ids):
    st.warning(
        f"No ratings found for user {user_id}. "
        f"Enter an ID between {min_id} and {max_id} that exists in the data."
    )
    st.stop()

st.subheader(f"Top 10 recommendations for user {user_id}")

recs = recommend(ubcf, user_id, min_ratings, top_n=10)

if not recs:
    st.warning("No books pass the filter - try lowering the minimum rating count.")
    # Clear stored candidates so the LLM section disappears too.
    st.session_state.pop("candidates", None)
else:
    rec_df = pd.DataFrame([
        {
            "book": c["title"],
            "# ratings": c["n_ratings"],
            "Avg rating (all users)": round(c["avg_rating"], 2),
            "Predicted (for this user)": round(c["predicted"], 2),
        }
        for c in recs
    ])
    rec_df.index = rec_df.index + 1
    rec_df.index.name = "Rank"
    st.dataframe(rec_df, use_container_width=True)

    # Save the candidates so the LLM section below has something to work with.
    st.session_state["candidates"] = recs

# ---- Context: what this user already likes ----
with st.expander(f"See what user {user_id} has already rated"):
    user_history = (
        ratings[ratings["user_id"] == user_id]
        .merge(books, on="book_id")
        [["title", "rating"]]
        .sort_values("rating", ascending=False)
        .reset_index(drop=True)
    )
    user_history.columns = ["Book", "Their rating"]
    user_history.index = user_history.index + 1
    st.dataframe(user_history, use_container_width=True)


# ---- LLM re-ranking (only shown once recs exist) ----
if "candidates" in st.session_state:
    st.divider()
    st.subheader("✨ Personalize with Gemini")
    st.caption(
        "Re-rank the recommendations above by your current mood. "
        "Each pick comes with a short explanation."
    )

    mood = st.text_input(
        "What are you in the mood for?",
        placeholder="e.g., something light and funny after a long day",
    )

    if st.button("Re-rank with Gemini", type="primary"):
        if get_gemini_client() is None:
            st.error(
                "Gemini API key not found. Add it to "
                ".streamlit/secrets.toml` as `GEMINI_API_KEY = \"...\"` "
                "or set the `GEMINI_API_KEY` environment variable, then restart "
                "the Streamlit app."
            )
        elif not mood.strip():
            st.warning("Tell me what you're in the mood for first.")
        else:
            with st.spinner("Asking Gemini to re-rank…"):
                try:
                    result = rerank_with_gemini(
                        st.session_state["candidates"],
                        mood.strip(),
                    )
                    out_df = pd.DataFrame([
                        {
                            "Book": m.title,
                            "Why it fits": m.reason,
                        }
                        for m in result
                    ])
                    out_df.index = out_df.index + 1
                    out_df.index.name = "Rank"
                    st.dataframe(out_df, use_container_width=True)
                except Exception as e:
                    st.error(f"Re-ranking failed: {e}")
